
services:
  postgres:
    image: postgres:15
    container_name: postgres_credito
    environment:
      POSTGRES_DB: credito_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - credito-network

networks:
  credito-network:
    driver: bridge
