/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.68).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.consulta.credito.controller;
import com.consulta.credito.dto.Credito;
import com.consulta.credito.dto.DetalhesCredito;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Validated
public interface ConsultaCreditoApi {

    @Operation(summary = "Consulta créditos por numeroNfse.", description = "Retorna uma lista de créditos.", tags={ "consultaCredito" })
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Consulta realizada com sucesso"),
        @ApiResponse(responseCode = "400", description = "Requisição inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        @ApiResponse(responseCode = "200", description = "Unexpected error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class)))})
    @RequestMapping(value = "/api/creditos/{numeroNfse}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Credito>> getConsultaCreditos(@Parameter(in = ParameterIn.PATH, description = "Consulta créditos por numeroNfse", required=true, schema=@Schema()) @PathVariable("numeroNfse") String numeroNfse
);


    @Operation(summary = "Consulta créditos por numeroCredito.", description = "Retorna os detalhes de um crédito constituído.", tags={ "consultaCredito" })
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Consulta realizada com sucesso"),
        @ApiResponse(responseCode = "400", description = "Requisição inválida", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        @ApiResponse(responseCode = "500", description = "Erro interno inesperado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class)))})
    @RequestMapping(value = "/api/creditos/credito/{numeroCredito}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<DetalhesCredito> getDetalhesCredito(@Parameter(in = ParameterIn.PATH, description = "Retorna os detalhes de um crédito constituído", required=true, schema=@Schema()) @PathVariable("numeroCredito") String numeroCredito
);

}

