FROM node:18 AS build
WORKDIR /front-end
COPY . .
RUN npm install && npm run build --prod

FROM nginx:alpine
COPY --from=build /front-end/dist/front-end/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80