FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /consulta-credito-api
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /consulta-credito-api
COPY --from=build /consulta-credito-api/target/consulta-credito-api-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]